{{- if and .Values.secrets.authTokens (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anyhost.fullname" . }}-auth
  labels:
    {{- include "anyhost.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.existingSecretKey }}: {{ .Values.secrets.authTokens | b64enc | quote }}
{{- end }}
